### ISSUE TITLE
Point cloud cannot show up on RViz

### ISSUE THREAD

**Issue by chungenyu6** [5VOXEL/voxel3d_ros#1]
My environment:
VirtualBox + Ubuntu 18.04 + ROS Melodic

I have successfully built and followed every instruction, everything seems correct, but when it comes to this command: 
**$ rosrun image_view image_view image:=/voxel3d/depth**

It only shows up :
**[ INFO] [1659429712.923210898]: Initializing nodelet with 1 worker threads.
[ INFO] [1659429713.046514006]: Using transport "raw"**

BTW, every instruction from the README.md, it won't show up any error.

My college has successfully done that it shows point cloud on RViz, with 8 worker threads working, but mine only has 1 worker thread.
Plus, that's the only difference between my result and his.

Thus, I want to know how to fix it, hope someone may help me with this, thank you.

**Comment by jackielee0424** [comment]
Hi,

Can you provide the full log of the roslaunch execution? (ex: roslaunch voxel3d_nodelet single_camera.launch)
The log will tell if camera is detected and also the published topics.

Assuming that device is detected and topics are as below
  [ INFO] [1659614048.232358755]: Topic : camera1/depth
  [ INFO] [1659614048.233373325]: Topic : camera1/confidence
  [ INFO] [1659614048.234121882]: Topic : camera1/points
  [ INFO] [1659614048.234852016]: Topic : camera1/camera_info

Use "rosrun image_view image_view image:=/voxel3d_nodelet_ns/camera1/confidence" to show the confidence image
or use "rosrun image_view image_view image:=/voxel3d_nodelet_ns/camera1/depth" to show the depth image.

5Voxel

**Comment by chungenyu6** [comment]
Sorry for the late reply.
Here/s the log when I execute : 
`roslaunch voxel3d_nodelet single_camera.launch`

BTW, the README.md of this package has a typo of this roslaunch command.

```
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.13
 * /voxel3d_nodelet_ns/camera1/auto_exposure: False
 * /voxel3d_nodelet_ns/camera1/camera: camera1
 * /voxel3d_nodelet_ns/camera1/conf_threshold: 40
 * /voxel3d_nodelet_ns/camera1/frame_id: odom
 * /voxel3d_nodelet_ns/camera1/range_mode: 2
 * /voxel3d_nodelet_ns/camera1/serial_number: 

NODES
  /voxel3d_nodelet_ns/
    camera1 (nodelet/nodelet)
    voxel3d_nodelet_manager (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

process[voxel3d_nodelet_ns/voxel3d_nodelet_manager-1]: started with pid [15298]
process[voxel3d_nodelet_ns/camera1-2]: started with pid [15299]
[ INFO] [1660187188.993296323]: Loading nodelet /voxel3d_nodelet_ns/camera1 of type voxel3d_nodelet/Voxel3dNodelet to manager voxel3d_nodelet_manager with the following remappings:
[ INFO] [1660187188.994456988]: waitForService: Service [/voxel3d_nodelet_ns/voxel3d_nodelet_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1660187189.009643668]: Initializing nodelet with 1 worker threads.
[ INFO] [1660187189.015164403]: waitForService: Service [/voxel3d_nodelet_ns/voxel3d_nodelet_manager/load_nodelet] is now available.
[ INFO] [1660187189.016814486]: camera1 : serial number - 
Selected 1st device with SN: PX2011090069
[ INFO] [1660187195.215956647]: camera1 : 5Voxel Library version - V1.1.1-958749e
[ INFO] [1660187195.223199764]: camera1 : 5Voxel 5Z01A FW version - V2.0.8-211291e
[ INFO] [1660187195.223687263]: camera1 : set range mode to 2
[ INFO] [1660187195.228527164]: camera1 : set confidence threshold to 40
[ INFO] [1660187195.247889691]: camera1 : disable auto exposure
[ INFO] [1660187195.255731802]: camera1 : set PointCloud2 frame id to odom
[ INFO] [1660187195.255812909]: Topic : camera1/depth
[ INFO] [1660187195.256375377]: Topic : camera1/confidence
[ INFO] [1660187195.256768652]: Topic : camera1/points
[ INFO] [1660187195.257068909]: Topic : camera1/camera_info
```

**Comment by jackielee0424** [comment]
Hi Chungen,

From the log, 5Voxel's ToF camera was detected correctly. Were you able to see any image by using image_view or rviz?
BTW, ToF needs higher peak current. So, please insert the module to USB 3.0 (or higher) port to ensure the power source is stable and sufficient. Since our ToF device is acting as a UVC camera, you can also use 'cheese' to open the device (ex: /dev/video0) and check if image is shown on it. (image with green color is normal since device streams depth/ir, not RGB image)

5Voxel

**Comment by chungenyu6** [comment]
I still cannot see any image by image_view nor rviz. Also, I've used "cheese" command to open the device

`$ cheese -d /dev/video0`

, and here's the error result:

```
(cheese:8135): Gtk-WARNING **: 11:13:25.391: Theme parsing error: cheese.css:7:35: The style property GtkScrollbar:min-slider-length is deprecated and shouldn't be used anymore. It will be removed in a future version

(cheese:8135): cheese-WARNING **: 11:13:25.501: Device '/dev/video0' is busy: gstv4l2object.c(3754): gst_v4l2_object_set_format_full (): /GstCameraBin:camerabin/GstWrapperCameraBinSrc:camera_source/GstBin:bin18/GstV4l2Src:v4l2src1:
Call to S_FMT failed for YUYV @ 448x172: Device or resource busy
```
And the message on the screen:
`There was an error playing video from the webcam.`

Is there any other way to solve it?

BTW my college installed ubuntu 18.04 directly on his PC, but I installed it on Virtualbox.
With the same ToF sensor, it can be run on his PC successfully.

**Comment by jackielee0424** [comment]
Hi Chungen,

We don't normally support VM since it may have compatibility issue on USB driver/wrapper. However, I did tried on virtual box installed on my laptop, and no issue on opening the 5Z01A camera. Not sure if it is related but I did enable USB 3.0 (xHCI) controller in my VM config.
   My virtual box version : 6.1.26 r145957 (Qt5.6.2)

Are you using laptop or desktop to run virtual box? Can you try on different USB port (some desktop front panel USB port has limited power)

5Voxel

**Comment by chungenyu6** [comment]
Thanks for giving the hint about enabling USB 3.0 (xHCI) in VBox, now the problem is fixed!

My original Vbox version : 6.1.26 r145957 (Qt5.6.2), which only has USB 1.0
And I tried to install **Virtualbox Extension Pack** from the official website; however, some errors showed up.
Thus, I reinstall Vbox with the version : 6.1.36 r152435, plus VirtualBox extension pack.
Then enable USB 3.0 in the settings, and follow the instructions of 5Voxel again.
Finally, it works.

Really appreciate your instant response.

**Comment by jackielee0424** [comment]
That's great! Thanks for letting me know the result.

5Voxel
