### ISSUE TITLE
support raspberry pi

### ISSUE THREAD

**Issue by chobitsfan** [5VOXEL/voxel3d_ros#2]
Would you be able to support raspberry pi ? It would be really helpful for drones application. Thank you very much.

**Comment by jackielee0424** [comment]
Sorry, not get notified somehow when issue was opened. We have library for raspberry pi4 in voxel3d_tools repo, but did not try with ros on pi4.

**Comment by chobitsfan** [comment]
Hi @jackielee0424 Thank you very much for replying. I will try it.
